name: Publish Nuget Packages

on:
  # the workflow run allows to not run the test suite twice for non release
  # branches, and should be used for all branches, but the reference branch
  # in workflow run is the default branch and we don't get the correct release
  # tags when it is triggered from release branches like stage and dev.
  workflow_run:
    workflows: ["Build and Test"]
    types: [completed]
    branches-ignore: [ stage, master ]

  # so we treat these releases branches specially, using the push trigger directly.
  push:
    branches: [ stage, master ]

  workflow_dispatch:
    inputs:
      semverIncrementLevel:
        description: "Level of the semver (major.minor.patch) to be increased to get the new package version."
        required: false
        default: "patch"
      debuggable:
        description: "Set to false if you want a non debuggable (Release) package."
        required: false
        default: "true"

env:
  ACTIONS_REF: feature/tag-action-upgrade

jobs:

  publish:

    runs-on: ubuntu-latest


    steps:
      - name: Checkout actions repo
        uses: actions/checkout@v3
        with:
          repository: trakx/github-actions
          path: github-actions
          ref: ${{env.ACTIONS_REF}}
        
      - name: Default input values
        id: default-inputs
        run: |
          debuggable="${{github.event.inputs.debuggable}}"
          debuggable=${debuggable:-true}
          echo "debuggable=$debuggable" >> $GITHUB_OUTPUT
          
          semverIncrementLevel="${{github.event.inputs.semverIncrementLevel}}"
          semverIncrementLevel=${semverIncrementLevel:-true}
          echo "semverIncrementLevel=$semverIncrementLevel" >> $GITHUB_OUTPUT

      - name: Build and publish nuget from feature-tag-action-upgrade
        id: publish
        uses: ./github-actions/publish-nuget
        with:
          actionsRef: ${{env.ACTIONS_REF}}
          packageReadonlyPat: ${{secrets.TRAKX_BOT_READONLY_PAT}}
          githubToken: ${{secrets.GITHUB_TOKEN}}
          debuggable: ${{steps.default-inputs.outputs.debuggable}}
          semverIncrementLevel: ${{steps.default-inputs.outputs.semverIncrementLevel}}
